### PR TITLE
Upgrade dependencies

### LINKED ISSUE #234: php-http/guzzle6-adapter Dependency Issue?
Hi All,

I'm currently installing to a Laravel code base using:

`composer require infusionsoft/php-sdk`

But I'm getting this error:

>   Problem 1
    - infusionsoft/php-sdk 1.4.9 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.8 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.7 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.6 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.5 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.4 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.3 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.2 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.1 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.0-beta requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - infusionsoft/php-sdk 1.4.0 requires php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1] but these conflict with your requirements or minimum-stability.
    - Installation request for infusionsoft/php-sdk ^1.4 -> satisfiable by infusionsoft/php-sdk[1.4.0, 1.4.0-beta, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9].

We're using Guzzle in other libraries but this error isn't being reported when we install them.

Any pointers?

### LINKED ISSUE #238: Unable to install infusionsoft/php-sdk on my PHP 7.3.8 setup.
```
$ php composer.phar require infusionsoft/php-sdk
Using version ^1.4 for infusionsoft/php-sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install infusionsoft/php-sdk 1.4.9
    - Conclusion: don't install infusionsoft/php-sdk 1.4.8
    - Conclusion: don't install infusionsoft/php-sdk 1.4.7
    - Conclusion: don't install infusionsoft/php-sdk 1.4.6
    - Conclusion: don't install infusionsoft/php-sdk 1.4.5
    - Conclusion: don't install infusionsoft/php-sdk 1.4.4
    - Conclusion: don't install infusionsoft/php-sdk 1.4.3
    - Conclusion: don't install infusionsoft/php-sdk 1.4.2
    - Conclusion: don't install infusionsoft/php-sdk 1.4.1
    - Installation request for infusionsoft/php-sdk ^1.4 -> satisfiable by infusionsoft/php-sdk[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9].
    - Conclusion: don't install lstrojny/fxmlrpc 0.8.4
    - infusionsoft/php-sdk 1.4.0 requires lstrojny/fxmlrpc ^0.14.0 -> satisfiable by lstrojny/fxmlrpc[0.14.0, 0.14.1].
    - Can only install one of: lstrojny/fxmlrpc[0.14.0, 0.8.4].
    - Can only install one of: lstrojny/fxmlrpc[0.14.1, 0.8.4].
    - Installation request for lstrojny/fxmlrpc (locked at 0.8.4) -> satisfiable by lstrojny/fxmlrpc[0.8.4].


Installation failed, reverting ./composer.json to its original content.
```

### PR DESCRIPTION
**Pull request by ajohnson6494**
This PR updates the composer dependencies.

Drops support for php 7 and 7.1 and adds support for php 7.3 and 7.4

Fixes #238 
Fixes #234 

Closes #236 as duplicate

### CODE REVIEW

**Comment by slavcodev** [comment]
Any chance this to be releazed? The current version blocks any usage of PSR-18 with HTTPplug.

**Comment by andriyPalko** [comment]
@ajohnson6494 I think would be better to change dependency from zendframework/zend-diactoros to laminas/laminas-diactoros as the first repository was abandoned and moved

@infusionsoft can you look at this please, for me it's critical now, also I think it's blocking a lot of your users, thanks

**Comment by Vakintoshka** [comment]
hey guys, any updates on it?

**Comment by SimplyCorey** [comment]
Wanting to tag along on this as well.  The old dependencies are starting to make upgrades impossible.

**Comment by SimplyCorey** [comment]
https://github.com/ajohnson6494/infusionsoft-php/releases seems to be a solution at this time for anyone looking for a solution.

@ajohnson6494 I appreciate your work, thank you.

**Review by jgourley — APPROVED** [review]

**Pull request merged**
